<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_enewsbqtemp_2`;");
E_C("CREATE TABLE `phome_enewsbqtemp_2` (
  `tempid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `tempname` varchar(60) NOT NULL DEFAULT '',
  `modid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `temptext` text NOT NULL,
  `showdate` varchar(50) NOT NULL DEFAULT '',
  `listvar` text NOT NULL,
  `subnews` smallint(5) unsigned NOT NULL DEFAULT '0',
  `rownum` smallint(5) unsigned NOT NULL DEFAULT '0',
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `docode` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`tempid`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=utf8");
E_D("replace into `phome_enewsbqtemp_2` values('1','ecms802-置顶推荐','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d','\$listtemp=\\\\''\r\n<article class=\\\\\"clr col-small\\\\\">\r\n  <div class=\\\\\"inner\\\\\">\r\n  <a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\" class=\\\\\"fancyimg home-blog-entry-thumb\\\\\">\r\n    <div class=\\\\\"thumb-img\\\\\">\r\n    <img class=\\\\\"box-hide\\\\\" src=\\\\\"/skin/ecms802/img/image-pending.gif\\\\\" data-original=\\\\\"\\\\''.sys_ResizeImg(\$r[titlepic]?\$r[titlepic]:\\\\\"/skin/ecmspic/random/titlepic/\\\\\".rand(1,15).\\\\\".jpg\\\\\",100,75,\\\\\"\\\\\").\\\\''\\\\\" alt=\\\\\"[!--title--]\\\\\">\r\n    <span><i class=\\\\\"fa fa-star\\\\\"></i></span>\r\n    </div>\r\n    </a>\r\n    <h3><a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></h3>\r\n    <p>[!--smalltext--] ··· </p>\r\n  </div>\r\n  <div class=\\\\\"meta\\\\\">\r\n  <span class=\\\\\"date\\\\\">[!--newstime--]</span>\r\n  <span class=\\\\\"views\\\\\"> 浏览: <script src=\\\\\"[!--news.url--]e/public/ViewClick/?classid=[!--classid--]&id=[!--id--]\\\\\"></script></span>\r\n  </div>\r\n</article>\r\n\\\\''; ','80','1','0','1');");
E_D("replace into `phome_enewsbqtemp_2` values('13','ecms802-最新文章','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$fr=\$empire->fetch1(\\\\\"select newstext from {\$dbtbpre}ecms_news_data_{\$r[stb]} where id=\\\\''\$r[id]\\\\''\\\\\");\r\n\$listtemp=\\\\''\r\n<article class=\\\\\"home-blog-entry col span_1 clr\\\\\">\r\n<a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\" class=\\\\\"fancyimg home-blog-entry-thumb\\\\\">\r\n  <div class=\\\\\"thumb-img\\\\\">\r\n  <img class=\\\\\"box-hide\\\\\" src=\\\\\"/skin/ecms802/img/image-pending.gif\\\\\" data-original=\\\\\"\\\\''.sys_ResizeImg(\$r[titlepic]?\$r[titlepic]:\\\\\"/skin/ecmspic/random/titlepic/\\\\\".rand(1,15).\\\\\".jpg\\\\\",280,210,\\\\\"\\\\\").\\\\''\\\\\" alt=\\\\\"[!--title--]\\\\\">\r\n  <span><i class=\\\\\"fa fa-expand\\\\\"></i></span>\r\n  </div>\r\n  </a>\r\n  <div class=\\\\\"home-blog-entry-text clr\\\\\">\r\n    <h3><a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></h3>\r\n    <div class=\\\\\"meta\\\\\">\r\n    <span class=\\\\\"postlist-meta-cat\\\\\"><i class=\\\\\"fa fa-bookmark\\\\\"></i>\r\n    <a href=\\\\\"[!--this.classlink--]\\\\\" rel=\\\\\"category tag\\\\\">[!--this.classname--]</a></span>\r\n    <span class=\\\\\"postlist-meta-time\\\\\"><i class=\\\\\"fa fa-calendar\\\\\"></i>[!--newstime--]</span>\r\n    <span class=\\\\\"postlist-meta-views\\\\\"><i class=\\\\\"fa fa-fire\\\\\"></i>浏览: <script src=\\\\\"[!--news.url--]e/public/ViewClick/?classid=[!--classid--]&id=[!--id--]\\\\\"></script></span>\r\n    <span class=\\\\\"postlist-meta-comments\\\\\"><i class=\\\\\"fa fa-comments\\\\\"></i>\r\n    <a href=\\\\\"[!--titleurl--]#comments\\\\\"><span>查看评论</span></a></span>\r\n    </div>\r\n    <p>\\\\''.esub(htmlspecialchars(strip_tags(str_replace(\\\\''&nbsp;\\\\'',\\\\''\\\\'',str_replace(\\\\''&ldquo;\\\\'',\\\\''\\\\'',str_replace(\\\\''&rdquo;\\\\'',\\\\''\\\\'',\$fr[newstext]))))),260).\\\\''</p>\r\n  </div>\r\n  <div class=\\\\\"clear\\\\\"></div>\r\n</article>\r\n\\\\''; ','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp_2` values('14','ecms802-热门动态','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','\$listtemp=\\\\''\r\n<article class=\\\\\"clr\\\\\">\r\n<a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\" class=\\\\\"fancyimg\\\\\">\r\n  <div class=\\\\\"thumb-img\\\\\">\r\n  <img class=\\\\\"box-hide\\\\\" src=\\\\\"/skin/ecms802/img/image-pending.gif\\\\\" data-original=\\\\\"\\\\''.sys_ResizeImg(\$r[titlepic]?\$r[titlepic]:\\\\\"/skin/ecmspic/random/titlepic/\\\\\".rand(1,15).\\\\\".jpg\\\\\",98,72,\\\\\"\\\\\").\\\\''\\\\\" alt=\\\\\"[!--title--]\\\\\"><span></span>\r\n  </div>\r\n  </a>\r\n  <h3><a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></h3>\r\n  <span class=\\\\\"reviewer\\\\\"><i class=\\\\\"fa fa-bookmark\\\\\"></i> \r\n  <a href=\\\\\"[!--this.classlink--]\\\\\" rel=\\\\\"category tag\\\\\">[!--this.classname--]</a></span> \r\n  <span class=\\\\\"date\\\\\">[!--newstime--]</span>\r\n  </article>\r\n\\\\''; ','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp_2` values('15','ecms802-焦点图','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li> \r\n<a class=\\\\\"slider-img\\\\\" href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">\r\n<img src=\\\\\"[!--titlepic--]\\\\\" alt=\\\\\"[!--title--]\\\\\"/>\r\n</a>\r\n  <h2><a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></h2>\r\n</li>\r\n','0','1','0','0');");
E_D("replace into `phome_enewsbqtemp_2` values('16','ecms802-滚动公告','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d H:i:s','<li class=\\\\\"sitenews-list\\\\\"><a href=\\\\\"[!--titleurl--]\\\\\" target=\\\\\"_blank\\\\\">[!--title--]</a></li>','0','1','0','0');");
E_D("replace into `phome_enewsbqtemp_2` values('17','ecms802-热门文章','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d','\$listtemp=\\\\''\r\n<li>\r\n  <div class=\\\\\"tab-item-thumbnail\\\\\">\r\n  <a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\">\r\n    <div class=\\\\\"thumb-img\\\\\">\r\n    <img class=\\\\\"box-hide\\\\\" src=\\\\\"/skin/ecms802/img/image-pending.gif\\\\\" data-original=\\\\\"\\\\''.sys_ResizeImg(\$r[titlepic]?\$r[titlepic]:\\\\\"/skin/ecmspic/random/titlepic/\\\\\".rand(1,15).\\\\\".jpg\\\\\",125,78,\\\\\"\\\\\").\\\\''\\\\\" alt=\\\\\"[!--title--]\\\\\" />\r\n    <span><i class=\\\\\"fa fa-expand\\\\\"></i></span></div>\r\n    </a></div>\r\n  <div class=\\\\\"tab-item-inner group\\\\\">\r\n    <p class=\\\\\"tab-item-title\\\\\">\r\n    <a href=\\\\\"[!--titleurl--]\\\\\" rel=\\\\\"bookmark\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a></p>\r\n    <span class=\\\\\"tab-item-date\\\\\">[!--newstime--]</span>&nbsp;<span class=\\\\\"tab-item-category\\\\\">\r\n    <a href=\\\\\"[!--this.classlink--]\\\\\" rel=\\\\\"category tag\\\\\">[!--this.classname--]</a>\r\n    </span>\r\n    </div>\r\n</li>\r\n\\\\''; ','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp_2` values('18','ecms802-内容页下热门文章','1','[!--empirenews.listtemp--]<!--list.var1-->[!--empirenews.listtemp--]','Y-m-d','\$listtemp=\\\\''\r\n<li>\r\n  <div class=\\\\\"relpost-inner\\\\\">\r\n    <div class=\\\\\"relpost-inner-pic\\\\\">\r\n    <a href=\\\\\"[!--titleurl--]\\\\\" title=\\\\\"[!--title--]\\\\\" class=\\\\\"\\\\\">\r\n      <div class=\\\\\"thumb-img\\\\\">\r\n      <img class=\\\\\"box-hide\\\\\" src=\\\\\"/skin/ecms802/img/image-pending.gif\\\\\" data-original=\\\\\"\\\\''.sys_ResizeImg(\$r[titlepic]?\$r[titlepic]:\\\\\"/skin/ecmspic/random/titlepic/\\\\\".rand(1,15).\\\\\".jpg\\\\\",200,125,\\\\\"\\\\\").\\\\''\\\\\" alt=\\\\\"[!--title--]\\\\\"> \r\n      <span><i class=\\\\\"fa fa-star\\\\\"></i></span>\r\n      </div>\r\n      </a>\r\n      </div>\r\n    <div class=\\\\\"relpost-inner-text\\\\\">\r\n    <a href=\\\\\"[!--titleurl--]\\\\\" rel=\\\\\"bookmark\\\\\" title=\\\\\"[!--title--]\\\\\">[!--title--]</a>\r\n    </div>\r\n  </div>\r\n  <div class=\\\\\"clear\\\\\"></div>\r\n</li>\r\n\\\\''; ','0','1','0','1');");
E_D("replace into `phome_enewsbqtemp_2` values('19','--------网站使用说明-----','1','感谢使用 李布斯（www.libusi.com）提供的网站模板。请大家自觉遵守法律规定,共同营造绿色的网络环境。\r\n\r\n安装前，一定要先清空FTP里面的老程序和数据库后，在上传程序进行安装。●非常重要●\r\n\r\n安装完成后，请及时更改后台地址和后台密码，不懂方法的，请看下面的教程。\r\n\r\n使用中如遇到问题，请不要着急，请看下面的教程，常见的问题都可以解决的。可以先看看。\r\n\r\n此模板的设定方法，请看这： http://www.libusi.com/1/802.html\r\n\r\n常见问题解决,安装方法,使用视频,请看这： http://www.libusi.com/1/edu1.html （不断更新中，此网址建议收藏）','Y-m-d H:i:s','感谢使用 李布斯（www.libusi.com）提供的网站模板。请大家自觉遵守法律规定,共同营造绿色的网络环境。','0','0','0','0');");

@include("../../inc/footer.php");
?>