<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `phome_enewspubvar`;");
E_C("CREATE TABLE `phome_enewspubvar` (
  `varid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `myvar` varchar(60) NOT NULL DEFAULT '',
  `varname` varchar(20) NOT NULL DEFAULT '',
  `varvalue` text NOT NULL,
  `varsay` varchar(255) NOT NULL DEFAULT '',
  `myorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `tocache` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`varid`),
  UNIQUE KEY `varname` (`varname`),
  KEY `classid` (`classid`),
  KEY `tocache` (`tocache`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=utf8");
E_D("replace into `phome_enewspubvar` values('1','ecms802-navigation-toggle','导航--手动加入的(顶上红色那两个按钮）','<li id=\"menu-item\" class=\"menu-item\"><a target=\"_blank\" href=\"http://www.libusi.com/tool/?url=http://802.libusi.com\"><font size=\"3\" face=\"arial\" color=\"red\"><i class=\"fa fa-apple\"> </i>   手机效果</font><span>iPhone</span></a></li>\r\n<li id=\"menu-item\" class=\"menu-item\"><a target=\"_blank\" href=\"http://www.libusi.com/1/ecms802.html\"><font size=\"3\" face=\"arial\" color=\"red\"><i class=\"fa fa-cny\"> </i>   购买模板</font><span>taobao</span></a></li>\r\n\r\n<!-- 请改为自已的或者“不写入缓存”就关闭了 -->','导航--手动加入的(顶上红色那两个按钮） ','1','0','1');");
E_D("replace into `phome_enewspubvar` values('2','802.libusi.com','---------网站使用说明-----','感谢使用 李布斯（www.libusi.com）提供的网站模板。请大家自觉遵守法律规定,共同营造绿色的网络环境。\r\n\r\n安装前，一定要先清空FTP里面的老程序和数据库后，在上传程序进行安装。●非常重要●\r\n\r\n安装完成后，请及时更改后台地址和后台密码，不懂方法的，请看下面的教程。\r\n\r\n使用中如遇到问题，请不要着急，请看下面的教程，常见的问题都可以解决的。可以先看看。\r\n\r\n此模板的设定方法，请看这： http://www.libusi.com/1/802.html\r\n\r\n常见问题解决,安装方法,使用视频,请看这： http://www.libusi.com/1/edu1.html （不断更新中，此网址建议收藏）','---------网站使用说明----- ','0','0','0');");
E_D("replace into `phome_enewspubvar` values('3','ecms802-changyan','搜狐畅言 ','<!--高速版-->\r\n<div id=\"SOHUCS\"></div>\r\n<script charset=\"utf-8\" type=\"text/javascript\" src=\"http://changyan.sohu.com/upload/changyan.js\" ></script>\r\n<script type=\"text/javascript\">\r\n    window.changyan.api.config({\r\n        appid: ''cys9POvoY'',\r\n        conf: ''prod_d54b641fe874037ce77b5d8278876ed3''\r\n    });\r\n</script>\r\n\r\n<!-- 上面为李布斯（www.libusi.com）的，请改为您自已的，没有的可以到搜狐畅言申请（ http://changyan.kuaizhan.com/ ）（此说明内容可删除） -->\r\n<!-- 如果搜狐畅言评论框有李布斯的网址和一些评论笑话，只要将畅言代码更换为您的就可以解决，改完重新刷新生成一下内容页和栏目页（此说明内容可删除）-->\r\n','搜狐畅言 ','3','0','1');");
E_D("replace into `phome_enewspubvar` values('4','ecms802-tongji-beian','备案号和统计代码 ','京ICP备0000000号-1\r\n\r\n<!-- 统计代码 -->\r\n<script type=''text/javascript'' src=''/tongji.js''></script>\r\n<!-- 请改为自已的-->\r\n','备案号和统计代码 ','4','0','1');");
E_D("replace into `phome_enewspubvar` values('5','ecms802-flashpic','焦点图 ','<li><a class=\"slider-img\" href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\"><img src=\"/skin/ecms802/img/JDTU01.jpg\" alt=\"购买模板\"/></a><h2><a href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\">购买模板</a></h2></li>\r\n<li><a class=\"slider-img\" href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\"><img src=\"/skin/ecms802/img/JDTU02.jpg\" alt=\"购买模板\"/></a><h2><a href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\">购买模板</a></h2></li>\r\n<li><a class=\"slider-img\" href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\"><img src=\"/skin/ecms802/img/JDTU03.jpg\" alt=\"购买模板\"/></a><h2><a href=\"http://www.libusi.com/1/ecms802.html\" title=\"购买模板\">购买模板</a></h2></li>\r\n\r\n\r\n<!-- 焦点图   可以通过设8级头条也行，两个二选一（注意图片大小），也可以“不写入缓存”，然后生成首页，这里的就不显示了  -->','首页焦点图 ','2','0','1');");
E_D("replace into `phome_enewspubvar` values('6','ecms802-sinaweibo-tencent-weibo','关注我们-微博(页顶）','<div id=\"focus-us\">\r\n关注我们<div id=\"focus-slide\" class=\"ie_pie\">\r\n<div class=\"focus-title\">关注我们</div>\r\n<p class=\"focus-content\">\r\n		<a href=\"http://weibo.com/12345678\" target=\"_blank\" class=\"sinaweibo\"><span><i class=\"fa fa-weibo\"></i>新浪微博</span></a>\r\n		<a href=\"http://t.qq.com/12345678\" target=\"_blank\" class=\"sinaweibo\"><span><i class=\"fa fa-tencent-weibo\"></i>腾讯微博</span></a>\r\n</p>\r\n</div></div>\r\n\r\n<!--  请改为自己的，或者 “不写入缓存” 就关闭了  -->','请改为自己的，或者不写入缓存就关闭了','3','0','1');");
E_D("replace into `phome_enewspubvar` values('7','ecms802-link','最下面右下角一堆图标的链接','	<span class=\"footer-aliyun-link\">\r\n		<a href=\"http://www.libusi.com/1/idc.html\" target=\"_blank\" class=\"aliyun\">\r\n			<span class=\"tinicon-aliyun\"><i class=\"fa fa-cloud\"></i></span>\r\n			<br>Aliyun\r\n		</a>\r\n	</span>\r\n		<span class=\"footer-sinaweibo-link\">\r\n		<a href=\"http://weibo.com/11111111111\" target=\"_blank\" class=\"sinaweibo\">\r\n			<span class=\"tinicon-sinaweibo\"><i class=\"fa fa-weibo\"></i></span>\r\n			<br>Weibo\r\n		</a>\r\n	</span>\r\n	 \r\n		<span class=\"footer-qq-link\">\r\n		<a href=\"http://wpa.qq.com/msgrd?v=3&uin=111111111111&site=qq&menu=yes\" target=\"_blank\" class=\"qq\">\r\n			<span class=\"tinicon-qq\"><i class=\"fa fa-qq\"></i></span>\r\n			<br>QQ\r\n		</a>\r\n	</span>\r\n	 \r\n	<span class=\"footer-rss-link\">\r\n		<a href=\"/e/web/?type=rss2&classid=0\" target=\"_blank\" class=\"rss\">\r\n			<span class=\"tinicon-rss\"><i class=\"fa fa-rss\"></i></span>\r\n			<br>RSS\r\n		</a>\r\n	</span>\r\n		<span class=\"footer-newsletter-link\">\r\n		<a href=\"mailto:00000@163.com\" target=\"_blank\" class=\"Email\">\r\n			<span class=\"tinicon-newsletter\"><i class=\"fa fa-envelope\"></i></span>\r\n			<br>Email\r\n		</a>\r\n	</span>','','9','0','1');");
E_D("replace into `phome_enewspubvar` values('8','ecms802-gybz','页脚-关于本站','  帝国CMS程序通过十多年的不断创新与完善，使系统集安全、稳定、强大、灵活于一身。并经过上千家知名网站的严格检测，被称为国内最安全、最稳定的开源CMS系统。感谢大家使用李布斯模板。自适应模板，同一个网址支持多种大小的显示屏显示。（此信息请到→系统→系统设置→扩展变量→页脚-关于本站→中修改。也可以选择“不写入缓存”，然后刷新生成所有页面，就可以不显示了。）','','8','0','1');");
E_D("replace into `phome_enewspubvar` values('9','ecms802-jrwm','页脚-加入我们','（此信息请到→系统→系统设置→扩展变量→页脚-加入我们→中修改。也可以选择“不写入缓存”，然后刷新生成所有页面，就可以不显示了。）','','8','0','1');");
E_D("replace into `phome_enewspubvar` values('10','ecms802-wzhz','页脚-网站合作','（此信息请到→系统→系统设置→扩展变量→页脚-网站合作→中修改。也可以选择“不写入缓存”，然后刷新生成所有页面，就可以不显示了。）','','8','0','1');");
E_D("replace into `phome_enewspubvar` values('11','ecms802-dibulink','底部链接','<li id=\"menu-item\" class=\"menu-item\"><a href=\"http://www.libusi.com/ecmsedu/\">使用技巧</a></li>\r\n<li id=\"menu-item\" class=\"menu-item\"><a href=\"http://www.libusi.com/\">李布斯</a></li>\r\n<li id=\"menu-item\" class=\"menu-item\"><a href=\"http://www.libusi.com/tool/?url=http://802.libusi.com\">手机效果</a></li>\r\n<li id=\"menu-item\" class=\"menu-item\"><a href=\"http://www.libusi.com/1/edu1.html\">常见问题</a></li>\r\n<li id=\"menu-item\" class=\"menu-item\"><a href=\"http://www.libusi.com/tool/\">自适应检测</a></li>','','9','0','1');");
E_D("replace into `phome_enewspubvar` values('12','ecms802-ad01','广告01','<div id=\"enhancedtextwidget-10\" class=\"widget widget_text enhanced-text-widget\">\r\n<div class=\"textwidget widget-text\">\r\n\r\n<a href=\"http://www.libusi.com/1/ecms802.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms802/img/a01.png\" alt=\"购买主题\"/></a>\r\n\r\n</div></div>','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('13','ecms802-ad02','广告02','<div id=\"enhancedtextwidget-11\" class=\"widget widget_text enhanced-text-widget\">\r\n<div class=\"textwidget widget-text\">\r\n\r\n<a href=\"http://www.libusi.com/1/ecms802.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms802/img/a02.png\" alt=\"购买主题\"/></a>\r\n\r\n</div></div>','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('14','ecms802-ad03','广告03','<div id=\"enhancedtextwidget-11\" class=\"widget widget_text enhanced-text-widget\">\r\n<div class=\"textwidget widget-text\">\r\n\r\n<a href=\"http://www.libusi.com/1/ecms802.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms802/img/a03.png\" alt=\"购买主题\"/></a>\r\n\r\n</div></div>','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('15','ecms802-ad04','广告04','<div id=\"singlethumb-banner\">\r\n\r\n<a href=\"http://www.libusi.com/1/ecms802.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms802/img/a04.png\" alt=\"购买主题\"/></a>\r\n\r\n</div>','','2','0','1');");
E_D("replace into `phome_enewspubvar` values('16','ecms802-ad05','广告05','<div id=\"cmnt-banner1\" class=\"banner\">\r\n\r\n<a href=\"http://www.libusi.com/1/ecms802.html\" target=\"_blank\">\r\n<img src=\"/skin/ecms802/img/a05.png\" alt=\"购买主题\"/></a>\r\n\r\n</div>','','2','0','1');");

@include("../../inc/footer.php");
?>